version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: your-backend-image-name
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=your-mongo-uri
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: your-frontend-image-name
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
